export default [
{
        "id": 1,
        "description":
          "Lenovo 100e 2nd Generation- 11.6in. Display, Intel Celeron N4020, 4GB RAM, 32GB eMMC Storage, Chrome OS, black",
        "name": "Lenovo 100e",
        "imagename": "Lenovo300e.png",
        "category": "Lenovo",
        "price": 100,
        "discount": 0,
        "stock": 2,
      },
   {
        "id": 2,
        "description":
          "HP Chromebook 11 G8 EE - 11.6in. HD Display, Intel Celeron N4020, 4GB RAM, 32GB eMMC Storage, Chrome OS, Grey",
        "name": "HP Chromebook 11 G8 EE",
        "imagename": "HPG8-11in.png",
        "category": "HP",
        "price": 120,
        "discount": 0.2,
        "stock": 0,
      },
        {
        "id": 3,
        "description":
          "HP Chromebook 11 G7 4gb RAM - 11.6in. HD Display, Intel Celeron N4000, 4GB RAM, 32GB eMMC Storage, Chrome OS, Grey",
        "name": "HP Chromebook 11 G7",
        "imagename": "HpG7.png",
        "category": "HP",
        "price": 100.0,
        "discount": 0.2,
          "stock": 4,
      },
      {
        "id": 3,
        "description":
          "HP Chromebook 11 G6 4gb RAM - 11.6in. HD Display, Intel Celeron N3350, 4GB RAM, 32GB eMMC Storage, Chrome OS, Grey",
        "name": "HP Chromebook 11 G6",
        "imagename": "hpChromebookG6.png",
        "category": "HP",
        "price": 90.0,
        "discount": 0.2,
          "stock": 6,
      },
           {
        "id": 4,
        "description":
          "HP Chromebook 11 G5 4gb RAM - 11.6in. HD Display, Intel Celeron N3350, 16GB eMMC Storage, Chrome OS, Silver and Black",
        "name": "HP Chromebook 11 G5",
        "imagename": "HpG5.png",
        "category": "HP",
        "price": 80.0,
        "discount": 0.2,
          "stock": 13,
      },
      {
        "id": 5,
        "description":
          "HP Chromebook G4 2gb RAM - 11.6in. HD Display, Intel Celeron N3060, 2GB RAM, 16GB eMMC Storage, Chrome OS, Silver and Black",
        "name": "HP Chromebook G4",
        "imagename": "HPcbg4.png",
        "category": "HP",
        "price": 60,
        "discount": 0,
          "stock": 10,
      },
      {
        "id": 6,
        "description":
          "Samsung Chromebook 4 - 11.6in. HD Display, Intel Celeron N4000, 4GB RAM, 32GB eMMC Storage, Chrome OS, Silver and Black",
        "name": "Samsung Chromebook 4",
        "imagename": "SamsungChromebook4.png",
        "category": "Samsung",
        "price": 100,
        "discount": 0.1,
        "stock": 1,
      },
      {
        "id": 7,
        "description": "Acer C733 - 11.6in. HD Display, Intel Celeron N3060, 4GB RAM, 32GB eMMC Storage, Chrome OS, Grey",
        "name": "Acer C733",
        "imagename": "AcerC733.png",
        "category": "Acer",
        "price": 100,
        "discount": 0,
        "stock": 1,
      },
      {
        "id": 8,
        "description": "Acer C731 - 11.6in. HD Display, Intel Celeron N3160, 4GB RAM, 16GB eMMC Storage, Chrome OS, Grey",
        "name": "Acer C731",
        "imagename": "AcerC731.png",
        "category": "Acer",
        "price": 80.0,
        "discount": 0,
        "stock": 1,
      },
      {
        "id": 9,
        "description":
          "Acer C730 - 11.6in. HD Display, Intel Celeron N2840, 2GB RAM, 16GB eMMC Storage, Chrome OS, Grey",
        "name": "Acer C730",
        "imagename": "AcerC730.png",
        "category": "Acer",
        "price": 60.0,
        "discount": 0,
        "stock": 1,
      }
]